#!/bin/bash

if [ ! -f config/config.php ]
then
cp config/config.php.example config/config.php
fi
if [ ! -f config/database.php ]
then
cp config/database.php.example config/database.php
fi
if [ ! -f config/parameters.php ]
then
cp config/parameters.php.example config/parameters.php
fi
if [ ! -f ../.htaccess ]
then
cp ../.htaccess.example ../.htaccess
fi

chmod -R 777 logs/
chmod 644 logs/.gitkeep
chmod -R 777 cache/
chmod 644 cache/.gitkeep
chmod 644 cache/smarty/.gitkeep
chmod 644 cache/twig/.gitkeep
chmod 644 cache/proxies/.gitkeep
chmod 644 cache/hydrators/.gitkeep
chmod -R 777 ../files/
chmod 644 ../files/.htaccess
chmod -R 777 ../thumbs/
chmod 644 ../thumbs/.htaccess
chmod -R 777 ../upload/
chmod 644 ../upload/.htaccess
chmod -R 777 backup/
chmod 644 backup/.gitkeep